name: Generate Snake Contribution Graph
on:
  schedule:
    - cron: "0 0 * * *"  # Runs once a day
  workflow_dispatch:      # Allows manual execution

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Generate Snake
        uses: Platane/snk@v3
        with:
          github_user_name: ${{ github.repository_owner }}
          outputs: dist/snake.svg

      - name: Commit and Push the Snake File
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"
          git add dist/snake.svg
          git commit -m "Generated snake contribution graph"
          git push
